// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA81BeS6ueoXuNEyS1UCeSgKVAZZeV84gk',
    appId: '1:640907091176:web:a34b184550be1396efbd5d',
    messagingSenderId: '640907091176',
    projectId: 'habit-tracker-de93b',
    authDomain: 'habit-tracker-de93b.firebaseapp.com',
    storageBucket: 'habit-tracker-de93b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtu5WC2fwZpWe2B_9wHQMembCljVjVMjg',
    appId: '1:640907091176:android:40acd463e211e946efbd5d',
    messagingSenderId: '640907091176',
    projectId: 'habit-tracker-de93b',
    storageBucket: 'habit-tracker-de93b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NYEbKCTovXiek8nYzStgI6wu064qn8Q',
    appId: '1:640907091176:ios:9cfd0b80aff26fd5efbd5d',
    messagingSenderId: '640907091176',
    projectId: 'habit-tracker-de93b',
    storageBucket: 'habit-tracker-de93b.firebasestorage.app',
    iosBundleId: 'com.riddhi.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NYEbKCTovXiek8nYzStgI6wu064qn8Q',
    appId: '1:640907091176:ios:9cfd0b80aff26fd5efbd5d',
    messagingSenderId: '640907091176',
    projectId: 'habit-tracker-de93b',
    storageBucket: 'habit-tracker-de93b.firebasestorage.app',
    iosBundleId: 'com.riddhi.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA81BeS6ueoXuNEyS1UCeSgKVAZZeV84gk',
    appId: '1:640907091176:web:7a8f5c0136ee1e1defbd5d',
    messagingSenderId: '640907091176',
    projectId: 'habit-tracker-de93b',
    authDomain: 'habit-tracker-de93b.firebaseapp.com',
    storageBucket: 'habit-tracker-de93b.firebasestorage.app',
  );
}
